version: "3.8"

# Created web network manually using docker command
networks:
  web:
    external: true
    driver: bridge

services:
  chrome:
    image: selenium/standalone-chrome:96.0
    hostname: chrome
    networks:
      - web
    privileged: true
    shm_size: 2g

  api:
    image: iusupov/traffic-jam:1.1.0
    ports:
      - "8080:8080"
    networks:
      - web
    depends_on:
      - chrome
#   You can override properties from application.yaml file here
#    environment:
#      TRAFFIC_URL: https://yandex.ru/maps/213/moscow/?l=trf%2Ctrfe&ll=37.659710%2C55.741284&utm_source=main_stripe_big&z=11.94
#      TRAFFIC_CSS_CLASS: traffic-raw-icon__text